import { Poppins } from "next/font/google";
import "./globals.css";
import Providers from "@/components/providers/Providers";
import BoxContainer from "@/components/ui/BoxContainer";
import "react-grid-layout/css/styles.css";
import "react-resizable/css/styles.css";

const poppins = Poppins({
    variable: "--font-poppins",
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${poppins.variable} font-poppins`}>
                {" "}
                <Providers>
                    <BoxContainer color="gray.fg">{children}</BoxContainer>
                </Providers>
            </body>
        </html>
    );
}
